#
# Travis configuration
#

# Source related
language: cpp
# Defined in CXX
compiler:
    - gcc
    - clang

before_install: "sudo ./scripts/install.sh"
install:
    - "cd ./libnei/build"
    - "qmake \"CONFIG+=test\""
    - "make"
script:
    - "./libnei_test"
    - "valgrind ./libnei_test"

# Branches
branches:
    only:
        - master
        - next

