#
# Travis configuration
#

# Source related
language: cpp
# Defined in CXX
compiler:
    - gcc
    - clang

before_install: "sudo ./scripts/install.sh"
install:
    - "cd ./libnei/build"
    - "qmake \"CONFIG+=test\""
    - "make"
script:
    - "cd .."
    - "./build/libnei_test"
    - "valgrind ./build/libnei_test"
    - "cppcheck -v --enable=all src test -I include --std=c++11 --suppress=missingIncludeSystem"

# Branches
branches:
    only:
        - master
        - next

